---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
